// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD32_2W6m46csvBW3c8ygH1Xt2QbqsO2GE',
    appId: '1:327074780511:web:b3c2a4ad6fcd5e4f7992ea',
    messagingSenderId: '327074780511',
    projectId: 'gymlog-eef4e',
    authDomain: 'gymlog-eef4e.firebaseapp.com',
    storageBucket: 'gymlog-eef4e.appspot.com',
    measurementId: 'G-TC7G3NHV3N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEHtOys3MhAQJ62dNVYBWJtXWLOA9rRyI',
    appId: '1:327074780511:android:7adfad1a03e2c3c57992ea',
    messagingSenderId: '327074780511',
    projectId: 'gymlog-eef4e',
    storageBucket: 'gymlog-eef4e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTBl2pnZTlBYKQCMMWWX5pviRNmdGevJE',
    appId: '1:327074780511:ios:e09866862207bb207992ea',
    messagingSenderId: '327074780511',
    projectId: 'gymlog-eef4e',
    storageBucket: 'gymlog-eef4e.appspot.com',
    iosBundleId: 'com.example.gymLog',
  );
}
